#!/usr/bin/env python3

import numpy as np
from numpy import pi
import socket
import time
import argparse
import subprocess

############################### Arguments parser #############################################

parser = argparse.ArgumentParser(description='CUBE pilot and momo')
parser.add_argument('--console_port',
					help="This is a second port generated by 01_socat.sh")
args = parser.parse_args()
CONSOLE_PORT = args.console_port

if CONSOLE_PORT is None:
	print("Error: please specify second port of socat generated")
	quit()

###################################SOCKET #############################################

SLU_FB_PORT = 31339
JETSON_IP = "192.168.8.26"
slu_fb_sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
slu_fb_sock.bind((JETSON_IP, SLU_FB_PORT))
slu_fb_sock.setblocking(0)

#################################### Loop #############################################

print("Started gps publisher thread")
prev_time = time.time()
try:
	while True:

		#######################################
		### Get feedback data from slu main ###
		#######################################

		try:
			while True:
				feedback_pkt, addr = slu_webrtc_sock.recvfrom(1024, socket.MSG_DONTWAIT)
				#print("got imu packet")
		except:
			feedback_pkt = webrtc_pkt

		if feedback_pkt:
			# Decode the input from momo
			feedback_pkt_dec = feedback_pkt.decode()
			


		#####################################
		### Publish data at specific rate ###
		#####################################
		## 0.01 -> 100 Hz
		## 0.05 -> 20  Hz
		## 0.1  -> 10  Hz
		## 0.5  -> 2   Hz
		if webrtc_pkt and ((time.time() - prev_time) > 0.1):
			print(feedback_pkt_dec)
			with open("camera_pos.txt", "w+")as file:
				file.write(feedback_pkt_dec)
			cmd1 = 'echo $(camera_pos.txt) > {:s}'.format(CONSOLE_PORT)
			subprocess.run(cmd1, shell=True, check=True)
			prev_time = time.time()


		time.sleep(0.001)

except Exception as e:
	print("ERROR as -> %s" %e)
	quit()
